### ISSUE TITLE
Jcenter is Forbidden

### ISSUE THREAD

**Issue by captain-miao** [hyy920109/HighLightPro#7]
Could not resolve com.github.hyy920109:GuidePro:1.1.3.
         > Could not get resource 'https://dl.bintray.com/umsdk/release/com/github/hyy920109/GuidePro/1.1.3/GuidePro-1.1.3.pom'.
            > Could not HEAD 'https://dl.bintray.com/umsdk/release/com/github/hyy920109/GuidePro/1.1.3/GuidePro-1.1.3.pom'. Received status code 403 from server: Forbidden

**Comment by hyy920109** [comment]
This library use jitpack not Jcenter. You should check your network first
