### ISSUE TITLE
建议在Constraints中添加水平，垂直居中的类型

### ISSUE THREAD

**Issue by Karl9452** [hyy920109/HighLightPro#8]

**Comment by hyy920109** [comment]
你这个水平和垂直居中是相对于谁来说的。手机屏幕吗？

**Comment by Karl9452** [comment]
@hyy920109 相对于focusView ，我在本地调整了一下，添加了水平居中:
`                Constraints.CenterHorizontalOfHighlight -> {
                    gravities.add(Gravity.CENTER_HORIZONTAL)
                }`

**Comment by hyy920109** [comment]
> @hyy920109 相对于focusView ，我在本地调整了一下，添加了水平居中:
> ` Constraints.CenterHorizontalOfHighlight -> { gravities.add(Gravity.CENTER_HORIZONTAL) }`

在源码上稍微修改一下就好了。后续我也可以给支持上  不过好多人的各种各样的需要确实没法完全满足

**Comment by nemo-ex** [comment]
支持下，居中的场景很常用

**Comment by wangbo666** [comment]
支持，居中的很常见

**Comment by hyy920109** [comment]
OK 我在源码种支持下吧

**Comment by hyy920109** [comment]
最新版本 1.4.0 以支持

**Comment by hyy920109** [comment]
如果有需要请升级后使用 demo中有示例
